modLoader="javafml"
loaderVersion="[47,)" # Forge version range
license="MIT"

[[mods]]
modId="magictp"
version="${mod_version}" # Use the user-facing version
displayName="Magic TP"
description='''
Magic TP makes teleportation magical!
More magic!
'''
authors="arsenius_gen"
logoFile="icon.png" # Path to the mod icon
displayURL="https://github.com/ArsenijN/MagicTP" # Link to the mod's site
credits="Special thanks to the Minecraft Forge team!"
issueTrackerURL="https://github.com/ArsenijN/MagicTP/issues"
